#!/bin/bash

apt-get update -y


apt-get install -y nginx


cat > /etc/nginx/sites-available/proxy.conf <<EOF
server {
    listen 80;

    location / {
        proxy_pass http://${private_alb_dns};
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF


rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/proxy.conf /etc/nginx/sites-enabled/proxy.conf


systemctl enable nginx
systemctl restart nginx